/* Generated by scripts/build-client.mjs; edit src/ instead. */
window.__ModuleLoader__.load({
  id: "dsh-activity-pane",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
// dsh-activity-pane 核心纯函数：把 DSH 原生 sessions/workspaces 客户端服务
// 快照映射成窗格里的"活动会话条目"。这一层不触碰 DOM，可单测。
//
// 数据源约定（来自 @deepseek-ai/dsh-client-runtime 的 sessions.list 快照）：
//   ids: SessionId[]                     —— 宿主列表顺序（祖先在前的 lineage 顺序）
//   byId[id]: { id, displayTitle, title?, cwd?, parentId?, running, completed?,
//              pendingInteraction?: 'approval'|'plan-review'|'question', blank, ... }
//   current: SessionId | undefined
//   subagentsByParent: { [parentId]: { entries: [{ id, label, ... }] } }
//   jobsBySession: { [sessionId]: JobView[] }
// 以及 workspaces.list 的 items: [{ title, path, sessionIds }]。
//
// 展示规则：
//   主会话（无有效 parentId）：running || completed || pendingInteraction 都显示；
//   子代理：仅 running || pendingInteraction 时显示（结束后即消失）；
//   pendingInteraction 总是优先视为"等待用户行动"（即使在 running 中）。

const PENDING_LABELS = {
	approval: "待确认",
	"plan-review": "待审查",
	question: "待回复",
};

function isRecord(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}

function cleanText(value) {
	return typeof value === "string" ? value.trim() : "";
}

/** 需要用户行动的种类的展示文案。 */
function pendingText(kind) {
	return PENDING_LABELS[kind] ?? "需要响应";
}

/** 会话 cwd 是否被某个 workspace 记录（含 title/path 两种命中）。 */
function workspaceTitleForSession(sessionId, workspaceItems, byId = {}) {
	const id = String(sessionId);
	const items = Array.isArray(workspaceItems) ? workspaceItems : [];

	for (const workspace of items) {
		if (!isRecord(workspace)) continue;
		const title = cleanText(workspace.title);
		if (!title || !Array.isArray(workspace.sessionIds)) continue;
		if (workspace.sessionIds.some((candidate) => String(candidate) === id))
			return title;
	}

	const cwd = cleanText(byId[id]?.cwd);
	if (!cwd) return "";
	const workspace = items.find(
		(candidate) => isRecord(candidate) && cleanText(candidate.path) === cwd,
	);
	return cleanText(workspace?.title);
}

/** 主会话按左侧工作区顺序排序的权重；不在任何 workspace 的排在最后保持 lineage 顺序。 */
function workspaceRank(workspaceItems) {
	const wsIndex = new Map();
	const posIndex = new Map();
	for (const workspace of workspaceItems ?? []) {
		if (!isRecord(workspace)) continue;
		const sessionIds = Array.isArray(workspace.sessionIds)
			? workspace.sessionIds
			: [];
		sessionIds.forEach((sid, p) => {
			const key = String(sid);
			if (!wsIndex.has(key)) {
				wsIndex.set(key, wsIndex.size);
				posIndex.set(key, p);
			}
		});
	}
	return (id) => {
		const key = String(id);
		return {
			ws: wsIndex.get(key) ?? Number.MAX_SAFE_INTEGER,
			pos: posIndex.get(key) ?? Number.MAX_SAFE_INTEGER,
		};
	};
}

/** 子代理的展示标题：优先目录 label，其次 displayTitle，兜底 "子任务"。 */
function subagentTitle(parentId, id, byId, subagentsByParent = {}) {
	const entries = subagentsByParent[parentId]?.entries;
	const entry = Array.isArray(entries)
		? entries.find((candidate) => String(candidate?.id) === String(id))
		: undefined;
	const label = cleanText(entry?.label);
	if (label) return label;
	const display = cleanText(byId[id]?.displayTitle);
	if (display) return display;
	return "子任务";
}

/** 主会话的展示标题：优先 displayTitle，兜底 "当前会话"。 */
function mainTitle(byId, id) {
	const display = cleanText(byId[id]?.displayTitle);
	return display || String(id) || "当前会话";
}

/**
 * 把 sessions/workspaces 快照构建成窗格条目列表（有序、已含层级与显示过滤）。
 * 返回数组的每一项：
 *   { id, depth, kind: 'running'|'awaiting'|'subagent', title, workspaceTitle,
 *     isCurrent, pendingText? }
 * kind 规则：
 *   - 主会话 running（且无 pending）→ 'running'
 *   - 主会话 pendingInteraction / completed → 'awaiting'（等待用户行动）
 *   - 子代理 running / pending → 'subagent'，否则不显示
 */
function buildEntries(snapshot, workspaceItems) {
	const byId = isRecord(snapshot) && isRecord(snapshot.byId) ? snapshot.byId : {};
	const ids = Array.isArray(snapshot?.ids) ? snapshot.ids : [];
	const current = snapshot?.current ?? null;
	const subagentsByParent = isRecord(snapshot?.subagentsByParent)
		? snapshot.subagentsByParent
		: {};
	const rank = workspaceRank(workspaceItems ?? []);

	// 第一遍：层级关系 + 显示判定。
	const rootIds = [];
	const childIds = new Map();
	const meta = new Map();
	for (const id of ids) {
		const row = byId[id];
		if (!isRecord(row)) continue;
		const parentId = row.parentId;
		const hasParent =
			parentId !== undefined && parentId !== null && isRecord(byId[parentId]);
		if (hasParent) {
			const list = childIds.get(String(parentId)) ?? [];
			list.push(id);
			childIds.set(String(parentId), list);
		} else {
			rootIds.push(id);
		}
		const running = row.running === true;
		const pending = row.pendingInteraction !== undefined;
		const isSub = hasParent;
		// 子代理完成后即消失；主会话完成后保留为"等待打开"。
		const show = isSub
			? running || pending
			: running || pending || row.completed === true;
		meta.set(id, { row, running, pending, isSub, show, depth: 0 });
	}

	// 主会话按 workspace 顺序排序；未归入任何工作区的主会话保持在 lineage 中靠后。
	rootIds.sort((a, b) => {
		const ra = rank(a);
		const rb = rank(b);
		if (ra.ws !== rb.ws) return ra.ws - rb.ws;
		if (ra.pos !== rb.pos) return ra.pos - rb.pos;
		return ids.indexOf(a) - ids.indexOf(b);
	});

	const entries = [];
	const visited = new Set();
	const visit = (id, depth) => {
		if (visited.has(id)) return;
		visited.add(id);
		const m = meta.get(id);
		if (m === undefined) return;
		m.depth = depth;
		if (m.show) {
			const parentId = m.row.parentId;
			entries.push({
				id,
				depth,
				kind: m.isSub ? "subagent" : m.pending ? "awaiting" : m.running ? "running" : "awaiting",
				title: m.isSub
					? subagentTitle(parentId, id, byId, subagentsByParent)
					: mainTitle(byId, id),
				workspaceTitle: m.isSub
					? ""
					: workspaceTitleForSession(id, workspaceItems ?? [], byId),
				isCurrent: current !== null && String(current) === String(id),
				pendingText: m.pending
					? pendingText(m.row.pendingInteraction)
					: m.row.completed === true && !m.running
						? "需要响应"
						: undefined,
			});
		}
		for (const child of childIds.get(id) ?? []) visit(child, depth + 1);
	};
	for (const root of rootIds) visit(root, 0);
	for (const id of ids) visit(id, 0);

	return entries;
}

/**
 * 渲染去重签名：两份条目序列若产出字节一致的可见状态则签名相等，
 * 因此渲染可跳过全部 DOM 写入，打破 渲染→写 DOM→再次触发渲染 的循环。
 */
function cardSignature(entries) {
	return JSON.stringify(
		entries.map((entry) => [
			entry.id,
			entry.depth,
			entry.kind,
			entry.title,
			entry.workspaceTitle,
			entry.isCurrent,
			entry.pendingText ?? null,
			entry.status ?? null,
			entry.updatedAt ?? null,
		]),
	);
}

// ---- 最近历史区（R-01-010）与轮内状态文案（R-01-009） ----

/** 历史窗口：会话最后一次活动距现在不超过该毫秒数则视为"最近使用过"。 */
const HISTORY_WINDOW_MS = 24 * 60 * 60 * 1000;
/** 历史区最多展示的最近会话条数。 */
const HISTORY_MAX = 20;

/** 会话行是否满足"活动区显示"判定（与 buildEntries 的 show 判定一致）。 */
function isActiveRow(row, byId = {}) {
	const parentId = row.parentId;
	const hasParent =
		parentId !== undefined && parentId !== null && isRecord(byId[parentId]);
	const running = row.running === true;
	const pending = row.pendingInteraction !== undefined;
	if (hasParent) return running || pending;
	return running || pending || row.completed === true;
}

/**
 * 构建最近历史区条目：当前非活动、但在历史窗口内最后一次活动过的会话，
 * 按最后活动时间从新到旧，最多 HISTORY_MAX 条。blank 会话不出现（从未用过）。
 */
function buildRecent(snapshot, workspaceItems, now, windowMs = HISTORY_WINDOW_MS) {
	const byId = isRecord(snapshot) && isRecord(snapshot.byId) ? snapshot.byId : {};
	const ids = Array.isArray(snapshot?.ids) ? snapshot.ids : [];
	const current = snapshot?.current ?? null;
	const items = Array.isArray(workspaceItems) ? workspaceItems : [];
	const entries = [];

	for (const id of ids) {
		const row = byId[id];
		if (!isRecord(row)) continue;
		if (row.blank === true) continue;
		if (isActiveRow(row, byId)) continue;
		const updatedAt = Number(row.updatedAt);
		if (!Number.isFinite(updatedAt)) continue;
		if (updatedAt > now || now - updatedAt > windowMs) continue;
		entries.push({
			id,
			kind: "recent",
			depth: 0,
			title: mainTitle(byId, id),
			workspaceTitle: workspaceTitleForSession(id, items, byId),
			isCurrent: current !== null && String(current) === String(id),
			updatedAt,
		});
	}

	entries.sort((a, b) => b.updatedAt - a.updatedAt);
	return entries.slice(0, HISTORY_MAX);
}

/** 毫秒时长的人性化短格式，例如 "47s"、"3m12s"。 */
function fmtElapsedMs(ms) {
	const s = Math.round(ms / 1000);
	if (s < 60) return `${s}s`;
	return `${Math.floor(s / 60)}m${s % 60}s`;
}

/**
 * 轮内状态文案：由渲染器把运行中会话的原生订阅快照映射为
 * `{ runningTool, streaming, elapsedMs }` 后调用。无任何宿主依赖。
 */
function statusLine({ runningTool = null, streaming = false, elapsedMs = null } = {}) {
	const head = runningTool
		? `工具：${runningTool}`
		: streaming
			? "正在回复…"
			: "运行中…";
	if (Number.isFinite(elapsedMs) && elapsedMs >= 0)
		return `${head} · ${fmtElapsedMs(elapsedMs)}`;
	return head;
}

// dsh-activity-pane 浏览器运行时。
//
// 挂载策略：把窗格作为 AppFrame 中 `conversation` 槽座的前置兄弟列插入
// （`#root [data-slot="conversation"] || .parentElement` 即 flex 行），让外壳的
// 让步链挤压中间栏；窄屏（<=767px）转为固定抽屉 + 浮动开关按钮。
//
// 数据来源：DSH 原生 `sessions` / `workspaces` 客户端服务（推送式快照）+ 对
// 运行中会话的原生订阅（binding().session），不依赖任何第三方插件数据路由，
// 也无需轮询。窗格内容分上下两段：上「活动会话」、下「最近历史」（24h）。

const name = "dsh-activity-pane";
const inject = [];

const CONVERSATION_SELECTOR = "#root [data-slot=\"conversation\"]";
const PANE_ATTR = "data-dsh-activity-pane";
const PANE_CLASS = "dap-pane";
const LIST_CLASS = "dap-list";
const RECENT_CLASS = "dap-recent";
const CARD_CLASS = "dap-card";
const STYLE_ID = "dsh-activity-pane-style";
const DEFAULT_WIDTH = 280;
const COLLAPSED_WIDTH = 34;
const INDENT_PX = 16;
const MOBILE_BREAKPOINT = "767px";
/** 运行卡时钟：只要存在运行中会话，就以该周期刷新时长显示。 */
const CLOCK_MS = 1000;

const CSS = `
[data-dsh-activity-pane] {
  --dap-width: ${DEFAULT_WIDTH}px;
  min-width: 0;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  box-sizing: border-box;
  border-right: 1px solid color-mix(in srgb, currentColor 12%, transparent);
  background: color-mix(in srgb, currentColor 3%, transparent);
  color: var(--dsw-alias-label-primary, #e8ebf2);
  user-select: none;
}
[data-dsh-activity-pane] .dap-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 12px;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.02em;
}
[data-dsh-activity-pane] .dap-count {
  flex: none;
  margin-left: auto;
  font-size: 10px;
  line-height: 16px;
  font-weight: 600;
  color: #221a10;
  background: linear-gradient(180deg, #ffd488, #e8a33d);
  border-radius: 999px;
  padding: 0 7px;
}
[data-dsh-activity-pane] .dap-count[data-awaiting] {
  background: linear-gradient(180deg, #ffb4b4, #f06a72);
  color: #2a1012;
  animation: dap-await-pulse 1.2s ease-in-out infinite;
}
@keyframes dap-await-pulse { 0%,100% { opacity: 1; } 50% { opacity: .55; } }
[data-dsh-activity-pane] .dap-collapse,
[data-dsh-activity-pane] .dap-close {
  flex: none;
  margin: 0;
  cursor: pointer;
  border: 1px solid color-mix(in srgb, currentColor 18%, transparent);
  border-radius: 999px;
  min-width: 20px;
  min-height: 20px;
  line-height: 18px;
  text-align: center;
  background: color-mix(in srgb, currentColor 10%, transparent);
  color: currentColor;
  padding: 0 5px;
}
[data-dsh-activity-pane] .dap-collapse { display: none; font-size: 13px; }
[data-dsh-activity-pane] .dap-close { display: none; font-size: 14px; }
/* 单一滚动区：活动区与最近历史同一容器滚动；touch-action/overscroll 防止
   触屏滚动穿透到下层页面（移动端「滚的是下面的会话界面」即根因）。 */
[data-dsh-activity-pane] .dap-scroll {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  overflow-x: hidden;
  overscroll-behavior: contain;
  touch-action: pan-y;
  -webkit-overflow-scrolling: touch;
  padding: 0 0 10px;
}
[data-dsh-activity-pane] .dap-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 0 8px;
}
/* 最近历史区：同一滚动区内的块段；整段可隐藏。 */
[data-dsh-activity-pane] .dap-recent {
  flex: none;
  display: flex;
  flex-direction: column;
  gap: 6px;
  border-top: 1px solid color-mix(in srgb, currentColor 10%, transparent);
  padding: 6px 8px 0;
  margin-top: 4px;
}
[data-dsh-activity-pane] .dap-recent[hidden] { display: none; }
[data-dsh-activity-pane] .dap-recent-head {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 2px 2px 0;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.06em;
  color: color-mix(in srgb, currentColor 52%, transparent);
  text-transform: uppercase;
}
/* 折叠：仅桌面生效；窄条 + 竖直计数。 */
[data-dsh-activity-pane] .dap-rail {
  display: none;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding-top: 10px;
}
[data-dsh-activity-pane] .dap-rail-count {
  min-width: 20px;
  height: 20px;
  border-radius: 999px;
  padding: 0 5px;
  text-align: center;
  line-height: 20px;
  font-size: 10px;
  font-weight: 700;
  background: color-mix(in srgb, currentColor 16%, transparent);
}
[data-dsh-activity-pane] .dap-rail-count[data-awaiting] {
  background: linear-gradient(180deg, #ffb4b4, #f06a72);
  color: #2a1012;
}
/* 桌面：窗格是中间列（position:relative）内的绝对定位左贴边列，位于侧栏旁；
   会话内容经 margin-left 推挤而非被覆盖。折叠时收窄为窄条。 */
@media (min-width: 768px) {
  [data-dsh-activity-pane] {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    width: var(--dap-width);
    z-index: 5;
  }
  [data-dsh-activity-pane] .dap-collapse { display: inline-block; }
  [data-dsh-activity-pane][data-collapsed="true"] { width: ${COLLAPSED_WIDTH}px; }
  [data-dsh-activity-pane][data-collapsed="true"] .dap-scroll,
  [data-dsh-activity-pane][data-collapsed="true"] .dap-count,
  [data-dsh-activity-pane][data-collapsed="true"] .dap-collapse { display: none; }
  [data-dsh-activity-pane][data-collapsed="true"] .dap-rail { display: flex; cursor: pointer; }
}
@media (max-width: ${MOBILE_BREAKPOINT}) {
  [data-dsh-activity-pane] .dap-close { display: inline-block; }
}
/* 卡片视觉沿用 answer-pet 的多会话卡片设计（MIT 参考，见 README）。 */
[data-dsh-activity-pane] .dap-card {
  flex: none;
  min-width: 0;
  padding: 9px 11px;
  border-radius: 14px;
  background: rgba(29, 31, 37, 0.94);
  border: 1px solid rgba(255, 255, 255, 0.13);
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.22);
  display: grid;
  gap: 4px;
  cursor: pointer;
}
[data-dsh-activity-pane] .dap-card:hover {
  border-color: rgba(255, 255, 255, 0.28);
}
[data-dsh-activity-pane] .dap-card:focus-visible {
  outline: 2px solid color-mix(in srgb, currentColor 70%, transparent);
  outline-offset: 2px;
}
[data-dsh-activity-pane] .dap-card[data-kind="subagent"] {
  padding: 6px 10px;
  border-radius: 12px;
  background: rgba(25, 27, 32, 0.95);
}
[data-dsh-activity-pane] .dap-card[data-kind="recent"] {
  padding: 6px 10px;
  border-radius: 12px;
  background: rgba(22, 24, 29, 0.9);
  border-color: transparent;
}
[data-dsh-activity-pane] .dap-card[data-current] {
  border-color: color-mix(in srgb, #65a0ff 75%, transparent);
  box-shadow: 0 0 0 1px color-mix(in srgb, #65a0ff 45%, transparent), 0 0 12px color-mix(in srgb, #65a0ff 30%, transparent);
}
[data-dsh-activity-pane] .dap-card[data-kind="awaiting"] {
  border-color: color-mix(in srgb, #e8a33d 55%, transparent);
  box-shadow: 0 0 0 1px color-mix(in srgb, #e8a33d 35%, transparent), 0 6px 16px rgba(0,0,0,.3);
  background: rgba(35, 31, 25, 0.97);
}
[data-dsh-activity-pane] .dap-card[data-opening] {
  opacity: 0.85;
  animation: dap-opening 0.9s ease-in-out infinite;
}
@keyframes dap-opening { 0%,100% { opacity: 0.95; } 50% { opacity: 0.5; } }
[data-dsh-activity-pane] .dap-row {
  display: flex;
  align-items: center;
  gap: 7px;
  min-width: 0;
}
[data-dsh-activity-pane] .dap-dot {
  width: 7px; height: 7px; flex: none; border-radius: 50%;
  background: #58c98f;
  box-shadow: 0 0 7px rgba(88,201,143,.8);
  animation: dap-pulse 1.2s ease-in-out infinite;
}
@keyframes dap-pulse { 0%,100% { opacity: 1; } 50% { opacity: .35; } }
[data-dsh-activity-pane] .dap-card[data-kind="awaiting"] .dap-dot {
  background: #e8a33d;
  box-shadow: 0 0 8px rgba(232,163,61,.85);
}
[data-dsh-activity-pane] .dap-card[data-kind="recent"] .dap-dot {
  background: #8a94a3;
  box-shadow: none;
  animation: none;
}
[data-dsh-activity-pane] .dap-title {
  flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis;
  white-space: nowrap; font-size: 12px; line-height: 16px; font-weight: 700;
}
[data-dsh-activity-pane] .dap-badge {
  flex: none; font-size: 10px; line-height: 14px; font-weight: 600;
  color: #221a10; background: linear-gradient(180deg, #ffd488, #e8a33d);
  border-radius: 999px; padding: 0 7px;
}
[data-dsh-activity-pane] .dap-workspace {
  width: fit-content; max-width: 100%; display: block;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  font-size: 9.5px; line-height: 14px;
  color: color-mix(in srgb, currentColor 90%, transparent);
  background: color-mix(in srgb, currentColor 11%, transparent);
  border: 1px solid color-mix(in srgb, currentColor 24%, transparent);
  border-radius: 999px; padding: 0 7px;
}
[data-dsh-activity-pane] .dap-workspace[hidden] { display: none; }
[data-dsh-activity-pane] .dap-note {
  min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  font-size: 11px; line-height: 15px;
  color: color-mix(in srgb, currentColor 62%, transparent);
}
[data-dsh-activity-pane] .dap-empty {
  padding: 14px 12px; font-size: 12px; text-align: center;
  color: color-mix(in srgb, currentColor 45%, transparent);
}
/* 移动端浮动开关按钮：仅在窄屏显示（桌面隐藏）。 */
.dap-toggle {
  position: fixed; top: 12px; right: 12px; z-index: 2147482991;
  display: none;
  align-items: center; gap: 6px;
  min-height: 30px; padding: 0 11px;
  border: 1px solid color-mix(in srgb, currentColor 18%, transparent);
  border-radius: 999px;
  background: rgba(24, 28, 38, 0.94);
  color: currentColor;
  font-size: 12px; font-weight: 600;
  cursor: pointer;
  box-shadow: 0 6px 16px rgba(0,0,0,.34);
}
.dap-toggle .dap-toggle-count {
  min-width: 16px; text-align: center; border-radius: 999px;
  background: color-mix(in srgb, currentColor 16%, transparent);
  padding: 0 5px; font-size: 10px; font-weight: 700;
}
.dap-toggle[data-awaiting] .dap-toggle-count {
  background: linear-gradient(180deg, #ffb4b4, #f06a72);
  color: #2a1012;
  animation: dap-await-pulse 1.2s ease-in-out infinite;
}
/* 窄屏：窗格变为固定抽屉 + 浮动开关按钮；抽屉默认隐藏在屏外。
   抽屉需不透明背景（否则透出下层会话内容）+ touch-action:none（把手/头部的
   触摸不滚动下层页面），桌面列则保持低透明分界。 */
@media (max-width: ${MOBILE_BREAKPOINT}) {
  [data-dsh-activity-pane] {
    position: fixed; left: 0; top: 0; bottom: 0;
    width: min(84vw, 320px);
    margin: 0;
    border-right: 1px solid currentColor;
    background: var(--dsw-alias-bg-layer-2, rgba(18, 21, 27, 0.97));
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    box-shadow: 8px 0 28px rgba(0,0,0,.5);
    transform: translateX(-102%);
    transition: transform 180ms ease;
    z-index: 2147482990;
    touch-action: none;
  }
  [data-dsh-activity-pane][data-open="true"] { transform: translateX(0); }
  .dap-toggle { display: flex; }
}
`;

function getSnapshot(service, key) {
	try {
		return service?.[key]?.getSnapshot?.() ?? null;
	} catch {
		return null;
	}
}

function schedule(callback) {
	if (typeof window.requestAnimationFrame === "function") {
		window.requestAnimationFrame(callback);
	} else {
		queueMicrotask(callback);
	}
}

/** 从原生会话快照归一为 statusLine 输入：工具名 / 是否流式 / 时长。 */
function livenessFromSnapshot(snap, now = Date.now()) {
	const runningCalls = Array.isArray(snap?.runningCalls) ? snap.runningCalls : [];
	const runningTool =
		runningCalls.length > 0 && runningCalls[0]?.name
			? String(runningCalls[0].name)
			: null;
	const streaming = snap?.partial != null && snap?.running !== false;
	let elapsedMs = null;
	const timings = snap?.turnTimings;
	if (timings instanceof Map) {
		for (const [_, timing] of timings) {
			if (
				timing &&
				Number.isFinite(timing.startTime) &&
				timing.endTime === undefined
			) {
				elapsedMs = now - timing.startTime;
				break;
			}
		}
	}
	return { runningTool, streaming, elapsedMs };
}

function fmtRecentTime(ts) {
	try {
		return `最近 ${new Date(ts).toLocaleTimeString([], {
			hour: "2-digit",
			minute: "2-digit",
		})}`;
	} catch {
		return "";
	}
}

function apply(ctx) {
	let disposed = false;
	let sessions = null;
	let workspaces = null;
	let sessionUnsubscribe = null;
	let workspaceUnsubscribe = null;
	let serviceTimer = null;
	let clockTimer = null;
	let syncScheduled = false;
	let lastSig = "";
	let collapsed = false;
	/** 活动区卡片 id → { el, kind } 复用表。 */
	const cardsById = new Map();
	/** 历史区卡片 id → { el } 复用表。 */
	const recentCardsById = new Map();
	/** 运行中会话轮内状态订阅：id → { unsubscribe, liveness }。 */
	const livenessById = new Map();

	const style = document.createElement("style");
	style.id = STYLE_ID;
	style.textContent = CSS;
	document.head.appendChild(style);

	// 移动端浮动开关按钮（桌面隐藏见 CSS）。
	const toggle = document.createElement("button");
	toggle.className = "dap-toggle";
	toggle.type = "button";
	toggle.setAttribute("aria-label", "切换活动会话窗格");
	toggle.innerHTML =
		"<span>活动会话</span><span class=\"dap-toggle-count\"></span>";
	document.body.appendChild(toggle);

	// 桌面判定与"会话区推挤"（pane 绝对定位贴左，会话内容以 margin 让位）。
	const desktopQuery = window.matchMedia("(min-width: 768px)");
	function applySeatMargin() {
		const seat = document.querySelector(CONVERSATION_SELECTOR);
		if (seat === null) return;
		const margin = desktopQuery.matches ? (collapsed ? COLLAPSED_WIDTH : DEFAULT_WIDTH) : 0;
		if (seat.style.marginLeft !== `${margin}px`) {
			seat.style.marginLeft = `${margin}px`;
			// 会话内容被右移只改变位置、不改变尺寸：ResizeObserver 不触发，依赖
			// `window resize` 重测的 sibling 插件（如 dsh-session-timeline）会停在
			// 旧位置并盖住本窗格。派发合成 resize 让它们按新布局重测。
			try {
				window.dispatchEvent(new Event("resize"));
			} catch {}
		}
	}

	function queueSync() {
		if (disposed || syncScheduled) return;
		syncScheduled = true;
		schedule(() => {
			syncScheduled = false;
			if (!disposed) render();
		});
	}

	function installServiceSubscriptions() {
		const nextSessions = ctx.get("sessions");
		const nextWorkspaces = ctx.get("workspaces");
		if (nextSessions === sessions && nextWorkspaces === workspaces) return;

		sessionUnsubscribe?.();
		workspaceUnsubscribe?.();
		sessions = nextSessions ?? null;
		workspaces = nextWorkspaces ?? null;
		sessionUnsubscribe = sessions?.list?.subscribe?.(queueSync) ?? null;
		workspaceUnsubscribe = workspaces?.list?.subscribe?.(queueSync) ?? null;

		if (sessions !== null && workspaces !== null && serviceTimer !== null) {
			clearInterval(serviceTimer);
			serviceTimer = null;
		}
		queueSync();
	}

	// ---- 窗格容器（conversation 槽座的前置兄弟列；外壳重挂载后重插） ----
	function ensurePane() {
		const seat = document.querySelector(CONVERSATION_SELECTOR);
		if (seat === null || seat.parentElement === null) return null;
		// [data-slot="conversation"] 的父级是 AppFrame 的中间列（flex column），
		// 它不是 grid 行——窗格不能插进该父级当块（会跑到会话上方）。改为在该
		// 父级内“绝对定位左贴边列”，并以其为定位上下文。
		const center = seat.parentElement;
		center.style.position = "relative";
		let pane = center.querySelector(`[${PANE_ATTR}]`);
		if (pane === null) {
			pane = document.createElement("aside");
			pane.setAttribute(PANE_ATTR, "");
			pane.className = PANE_CLASS;
			center.appendChild(pane);
			pane.innerHTML = `
				<div class="dap-header">
					<span>活动会话</span>
					<span class="dap-count" role="status" aria-live="polite"></span>
					<button class="dap-collapse" type="button" aria-label="收起窗格" title="收起">«</button>
					<button class="dap-close" type="button" aria-label="收起抽屉">×</button>
				</div>
				<div class="dap-scroll">
					<div class="dap-list" tabindex="-1"></div>
					<div class="dap-recent">
						<div class="dap-recent-head"><span>最近历史 · 24h</span></div>
					</div>
				</div>
				<div class="dap-rail">
					<span class="dap-rail-count" role="status" aria-live="polite"></span>
				</div>
			`;
		}
		return pane;
	}

	function makeEl(tag, cls) {
		const node = document.createElement(tag);
		if (cls) node.className = cls;
		return node;
	}

	/** 静态骨架卡片；动态文本一律走 textContent，规避 HTML 注入。 */
	function cardChildren(kind) {
		if (kind === "subagent") {
			const row = makeEl("div", "dap-row");
			row.append(makeEl("span", "dap-dot"), makeEl("span", "dap-title"));
			return [row];
		}
		if (kind === "recent") {
			const row = makeEl("div", "dap-row");
			row.append(makeEl("span", "dap-dot"), makeEl("span", "dap-title"));
			return [row, makeEl("div", "dap-note")];
		}
		if (kind === "awaiting") {
			const row = makeEl("div", "dap-row");
			row.append(
				makeEl("span", "dap-dot"),
				makeEl("span", "dap-title"),
				makeEl("span", "dap-badge"),
			);
			return [makeEl("div", "dap-workspace"), row, makeEl("div", "dap-note")];
		}
		const row = makeEl("div", "dap-row");
		row.append(makeEl("span", "dap-dot"), makeEl("span", "dap-title"));
		return [makeEl("div", "dap-workspace"), row, makeEl("div", "dap-note")];
	}

	function renderCardInto(el, entry) {
		const workspaceLabel = el.querySelector(".dap-workspace");
		if (workspaceLabel !== null) {
			if (entry.workspaceTitle !== "") {
				workspaceLabel.textContent = entry.workspaceTitle;
				workspaceLabel.removeAttribute("hidden");
			} else {
				workspaceLabel.textContent = "";
				workspaceLabel.setAttribute("hidden", "");
			}
		}
		const title = el.querySelector(".dap-title");
		if (title !== null && title.textContent !== entry.title)
			title.textContent = entry.title;

		const badge = el.querySelector(".dap-badge");
		if (badge !== null && badge.textContent !== (entry.pendingText ?? ""))
			badge.textContent = entry.pendingText ?? "";

		const note = el.querySelector(".dap-note");
		if (note !== null) {
			const next =
				entry.kind === "running"
					? (entry.status ?? "运行中…")
					: entry.kind === "awaiting"
						? entry.pendingText === "需要响应"
							? "本轮已完成，等待你处理"
							: `等待你的回应（${entry.pendingText}）`
						: entry.kind === "recent"
							? fmtRecentTime(entry.updatedAt)
							: "";
			if (note.textContent !== next) note.textContent = next;
		}
	}

	// ---- 轮内状态订阅生命周期（R-01-009、R-02-004） ----
	function syncLiveness(runningIds) {
		for (const id of runningIds) {
			if (livenessById.has(id)) continue;
			let session = null;
			try {
				session = sessions?.binding?.(id)?.session ?? null;
			} catch {
				session = null;
			}
			if (session === null) continue; // 下次渲染再试
			let unsubscribe = null;
			unsubscribe = session.subscribe(() => {
				if (disposed) return;
				const live = livenessFromSnapshot(getSessionSnapshot(session));
				livenessById.set(id, { unsubscribe, liveness: live });
				queueSync();
			});
			livenessById.set(id, {
				unsubscribe,
				liveness: livenessFromSnapshot(getSessionSnapshot(session)),
			});
		}
		for (const [id, rec] of livenessById) {
			if (runningIds.has(id)) continue;
			try {
				rec.unsubscribe?.();
			} catch {}
			livenessById.delete(id);
		}
		// 运行卡时钟：有运行中会话才启动，无则停。
		if (runningIds.size > 0 && clockTimer === null) {
			clockTimer = setInterval(() => queueSync(), CLOCK_MS);
		} else if (runningIds.size === 0 && clockTimer !== null) {
			clearInterval(clockTimer);
			clockTimer = null;
		}
	}

	function getSessionSnapshot(session) {
		try {
			return session?.getSnapshot?.() ?? null;
		} catch {
			return null;
		}
	}

	/** 保证 list 内存在/移除空态节点（R-01-001/AC-02）。 */
	function ensureEmpty(list, show, text) {
		let node = list.querySelector(".dap-empty");
		if (show) {
			if (node === null) {
				node = makeEl("div", "dap-empty");
				list.appendChild(node);
			}
			if (node.textContent !== text) node.textContent = text;
		} else if (node !== null) {
			node.remove();
		}
	}

	/** 渲染某一张卡片进指定列表容器（活动/历史通用）。 */
	function renderCardIntoList(list, entry, reuseMap) {
		let rec = reuseMap.get(entry.id);
		if (rec === undefined) {
			const el = document.createElement("div");
			el.className = CARD_CLASS;
			rec = { el, kind: null };
			reuseMap.set(entry.id, rec);
		}
		if (rec.kind !== entry.kind) {
			rec.el.dataset.kind = entry.kind;
			rec.el.dataset.sessionId = entry.id;
			rec.el.dataset.depth = String(entry.depth ?? 0);
			rec.el.setAttribute("role", "button");
			rec.el.tabIndex = 0;
			rec.el.replaceChildren(...cardChildren(entry.kind));
			rec.kind = entry.kind;
		}
		rec.el.style.marginLeft = `${(entry.depth ?? 0) * INDENT_PX}px`;
		rec.el.toggleAttribute("data-current", entry.isCurrent);
		rec.el.toggleAttribute("data-awaiting", entry.kind === "awaiting");
		rec.el.setAttribute(
			"aria-label",
			`${entry.workspaceTitle ? entry.workspaceTitle + " - " : ""}${entry.title}${
				entry.pendingText ? "，" + entry.pendingText : ""
			}`,
		);
		renderCardInto(rec.el, entry);
		list.appendChild(rec.el);
		return true;
	}

	function pruneCards(reuseMap, alive) {
		for (const [id, rec] of reuseMap) {
			if (alive.has(id)) continue;
			rec.el.remove();
			reuseMap.delete(id);
		}
	}

	function render() {
		const pane = ensurePane();
		if (pane === null) return;
		applySeatMargin();
		const activeList = pane.querySelector(`.${LIST_CLASS}`);
		const recentSection = pane.querySelector(`.${RECENT_CLASS}`);
		if (activeList === null || recentSection === null) return;

		const snapshot = getSnapshot(sessions, "list");
		const workspaceItems = getSnapshot(workspaces, "list")?.items ?? [];
		const now = Date.now();

		const active = buildEntries(snapshot, workspaceItems);
		const runningIds = new Set(
			active
				.filter((entry) => entry.kind === "running")
				.map((entry) => entry.id),
		);
		syncLiveness(runningIds);
		for (const entry of active) {
			if (entry.kind === "running") {
				entry.status = statusLine(
					livenessById.get(entry.id)?.liveness ?? {},
				);
			}
		}
		const recent = buildRecent(snapshot, workspaceItems, now);

		const sig = cardSignature([...active, ...recent]);
		if (sig === lastSig) return;
		lastSig = sig;

		const aliveActive = new Set();
		for (const entry of active)
			if (renderCardIntoList(activeList, entry, cardsById))
				aliveActive.add(entry.id);
		pruneCards(cardsById, aliveActive);
		ensureEmpty(activeList, active.length === 0, "暂无活动会话");

		const aliveRecent = new Set();
		for (const entry of recent)
			if (renderCardIntoList(recentSection, entry, recentCardsById))
				aliveRecent.add(entry.id);
		pruneCards(recentCardsById, aliveRecent);
		if (recentSection !== null) recentSection.hidden = recent.length === 0;

		// 计数与折叠
		const count = pane.querySelector(".dap-count");
		const railCount = pane.querySelector(".dap-rail-count");
		const hasAwaiting = active.some((entry) => entry.kind === "awaiting");
		for (const el of [count, railCount])
			if (el !== null) {
				el.textContent = String(active.length);
				el.toggleAttribute("data-awaiting", hasAwaiting);
			}
		const toggleCount = toggle.querySelector(".dap-toggle-count");
		if (toggleCount !== null) {
			toggleCount.textContent = String(active.length);
			toggle.toggleAttribute("data-awaiting", hasAwaiting);
		}
		pane.toggleAttribute("data-collapsed", collapsed ? "true" : "false");
	}

	// ---- 打开会话（复用 companion 验证过的：list 未就绪时 refresh + 重试） ----
	const MAX_OPEN_ATTEMPTS = 60;
	function sessionsListHas(sessionId) {
		const snap = getSnapshot(sessions, "list");
		return (
			snap !== null &&
			Array.isArray(snap.ids) &&
			snap.ids.includes(String(sessionId))
		);
	}
	function cardElFor(sessionId) {
		return document.querySelector(
			`[${PANE_ATTR}] [data-session-id="${String(sessionId)
				.replace(/"/g, '\\"')
				.replace(/\\/g, "\\\\")}"]`,
		);
	}
	function attemptOpen(sessionId, attempt) {
		const el = cardElFor(sessionId);
		if (el !== null) el.setAttribute("data-opening", "");

		if (!sessionsListHas(sessionId)) {
			if (attempt < MAX_OPEN_ATTEMPTS) {
				try {
					sessions.refresh?.();
				} catch {}
				setTimeout(() => attemptOpen(sessionId, attempt + 1), 500);
				return;
			}
			el?.removeAttribute("data-opening");
			return;
		}
		try {
			sessions.open(sessionId);
			el?.removeAttribute("data-opening");
		} catch (error) {
			if (attempt < MAX_OPEN_ATTEMPTS) {
				try {
					sessions.refresh?.();
				} catch {}
				setTimeout(() => attemptOpen(sessionId, attempt + 1), 500);
			} else {
				el?.removeAttribute("data-opening");
			}
		}
	}
	/** 纯几何命中 + capture 阶段点击，规避覆盖层/stopPropagation。 */
	function sessionIdAtPoint(x, y) {
		if (typeof x !== "number" || typeof y !== "number") return undefined;
		const cards = Array.from(
			document.querySelectorAll(`[${PANE_ATTR}] [data-session-id]`),
		);
		for (const card of cards) {
			const r = card.getBoundingClientRect();
			if (r.left <= x && x <= r.right && r.top <= y && y <= r.bottom)
				return card.dataset.sessionId;
		}
		return undefined;
	}
	function openCard(event) {
		// 守卫：只处理落在窗格内部的点击，任何主会话区/外壳点击都不拦截。
		if (!event.target?.closest?.(`[${PANE_ATTR}]`)) return;
		const sessionId =
			sessionIdAtPoint(event.clientX, event.clientY) ??
			event.target
				?.closest?.(`[${PANE_ATTR}] [data-session-id]`)
				?.dataset?.sessionId;
		if (sessionId === undefined) return;
		if (typeof sessions?.open !== "function") return;
		event.preventDefault();
		event.stopPropagation();
		attemptOpen(sessionId, 0);
	}
	function onKeyDown(event) {
		if (event.key !== "Enter" && event.key !== " ") return;
		const card = event.target?.closest?.(`[${PANE_ATTR}] [data-session-id]`);
		if (card?.dataset.sessionId === undefined) return;
		event.preventDefault();
		attemptOpen(card.dataset.sessionId, 0);
	}

	// ---- 观察者：找到 frame 后聚焦其子树；外壳重挂载时窗格被清即重插 ----
	const bodyObserver = new MutationObserver(queueSync);
	bodyObserver.observe(document.body, { childList: true, subtree: true });
	let frameObserver = null;
	let frameProbeTimer = null;
	function installFrameObserver() {
		if (frameObserver !== null) return;
		const seat = document.querySelector(CONVERSATION_SELECTOR);
		if (seat === null || seat.parentElement === null) return;
		bodyObserver.disconnect();
		frameObserver = new MutationObserver(queueSync);
		frameObserver.observe(seat.parentElement, {
			childList: true,
			subtree: true,
		});
		if (frameProbeTimer !== null) {
			clearInterval(frameProbeTimer);
			frameProbeTimer = null;
		}
	}
	installFrameObserver();
	if (frameObserver === null) frameProbeTimer = setInterval(installFrameObserver, 500);

	// ---- 交互：移动端抽屉开关、弹窗收起、桌面折叠 ----
	function togglePane(open) {
		const pane = document.querySelector(`[${PANE_ATTR}]`);
		if (pane === null) return;
		pane.setAttribute("data-open", open ? "true" : "false");
	}
	function onToggleClick() {
		const pane = document.querySelector(`[${PANE_ATTR}]`);
		const open = pane?.getAttribute("data-open") !== "true";
		togglePane(open);
	}
	function onPaneClick(event) {
		const inPane = event.target?.closest?.(`[${PANE_ATTR}]`) !== null;
		if (inPane && event.target?.closest?.(".dap-close") !== null) {
			togglePane(false);
			return;
		}
		if (inPane && event.target?.closest?.(".dap-collapse") !== null) {
			collapsed = !collapsed;
			const pane = document.querySelector(`[${PANE_ATTR}]`);
			pane?.setAttribute("data-collapsed", collapsed ? "true" : "false");
			return;
		}
		if (inPane && event.target?.closest?.(".dap-rail") !== null) {
			collapsed = false;
			const pane = document.querySelector(`[${PANE_ATTR}]`);
			pane?.setAttribute("data-collapsed", "false");
		}
	}
	toggle.addEventListener("click", onToggleClick);
	document.addEventListener("click", onPaneClick);
	const onResize = () => queueSync();
	desktopQuery.addEventListener("change", onResize);

	installServiceSubscriptions();
	if (sessions === null || workspaces === null) {
		serviceTimer = setInterval(installServiceSubscriptions, 250);
	}
	document.addEventListener("click", openCard, true); // capture
	document.addEventListener("keydown", onKeyDown);
	queueSync();

	return () => {
		disposed = true;
		sessionUnsubscribe?.();
		workspaceUnsubscribe?.();
		if (serviceTimer !== null) clearInterval(serviceTimer);
		if (clockTimer !== null) clearInterval(clockTimer);
		for (const [, rec] of livenessById) {
			try {
				rec.unsubscribe?.();
			} catch {}
		}
		livenessById.clear();
		bodyObserver.disconnect();
		frameObserver?.disconnect();
		if (frameProbeTimer !== null) clearInterval(frameProbeTimer);
		toggle.removeEventListener("click", onToggleClick);
		document.removeEventListener("click", onPaneClick);
		desktopQuery.removeEventListener("change", onResize);
		const seat = document.querySelector(CONVERSATION_SELECTOR);
		if (seat !== null) seat.style.marginLeft = "";
		document.removeEventListener("click", openCard, true);
		document.removeEventListener("keydown", onKeyDown);
		toggle.remove();
		style.remove();
	};
}

module.exports = { name, inject, apply };

    return module.exports;
  }
});
