import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const core = (await readFile(join(root, 'src/core.mjs'), 'utf8')).replace(/^export\s+/gm, '')
const client = await readFile(join(root, 'src/client.mjs'), 'utf8')
const bundle = `/* Generated by scripts/build-client.mjs; edit src/ instead. */
window.__ModuleLoader__.load({
  id: "dsh-activity-pane",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${core}
${client}
    return module.exports;
  }
});
`
await writeFile(join(root, '.dsh-plugin/client.js'), bundle)
