import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/**
 * 生成 .dsh-plugin/client.js。使用原地写入（fs.writeFile 截断同一文件），
 * 保证以 `file:` 依赖安装进 profile 时的硬链接 inode 不被破坏——这样写一次
 * 既能更新 source 副本，也能即时刷新 DSH 服务器侧面 HMR 监视的那个 bundle
 * 文件。watch.mjs 与 check.mjs 都调用本函数。
 */
export async function build() {
	const core = (await readFile(join(root, 'src/core.mjs'), 'utf8')).replace(
		/^export\s+/gm,
		'',
	)
	const client = await readFile(join(root, 'src/client.mjs'), 'utf8')
	const bundle = `/* Generated by scripts/build-client.mjs; edit src/ instead. */
window.__ModuleLoader__.load({
  id: "dsh-activity-pane",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${core}
${client}
    return module.exports;
  }
});
`
	await writeFile(join(root, '.dsh-plugin/client.js'), bundle)
}

// CLI 入口：node scripts/build-client.mjs
if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
	build().catch((error) => {
		console.error(error)
		process.exit(1)
	})
}
