import { readFile, rename, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/**
 * 生成 .dsh-plugin/client.js。采用"写临时文件 + 原子 rename"，保证任何并发写入
 * 或 HTTP 读取都只看到完整文件（杜绝就地截断写入的撕裂竞态）；profile 侧经
 * `link:` 符号链接指向本仓库，rename 后立即可见，HMR 的 stat-poll 照常触发。
 */
export async function build() {
	const core = (await readFile(join(root, 'src/core.mjs'), 'utf8')).replace(
		/^export\s+/gm,
		'',
	)
	const navigation = (await readFile(join(root, 'src/navigation.mjs'), 'utf8')).replace(
		/^export\s+/gm,
		'',
	)
	const client = await readFile(join(root, 'src/client.mjs'), 'utf8')
	const bundle = `/* Generated by scripts/build-client.mjs; edit src/ instead. */
window.__ModuleLoader__.load({
  id: "dsh-activity-pane",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${core}
${navigation}
${client}
    return module.exports;
  }
});
`
	const tmp = join(root, '.dsh-plugin/client.js.tmp')
	await writeFile(tmp, bundle)
	await rename(tmp, join(root, '.dsh-plugin/client.js'))
}

// CLI 入口：node scripts/build-client.mjs
if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
	build().catch((error) => {
		console.error(error)
		process.exit(1)
	})
}
